# Generated by Django 3.0.5 on 2020-06-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='image_url',
            field=models.CharField(default='https://i.pinimg.com/originals/c4/ce/87/c4ce878870d075fcda7b6a40114f1757.gif', max_length=100),
        ),
    ]
