# Generated by Django 3.0.5 on 2020-06-17 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_shoe_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='avg_price',
            new_name='purchased_price',
        ),
    ]
