# Generated by Django 3.0.5 on 2020-06-17 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200617_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='image_url',
            field=models.CharField(default='https://i.pinimg.com/originals/c4/ce/87/c4ce878870d075fcda7b6a40114f1757.gif', max_length=200),
        ),
    ]
