# Generated by Django 3.0.5 on 2020-06-18 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200617_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recently_Sold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='sold date')),
                ('sold_price', models.IntegerField()),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Shoe')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
