# Generated by Django 3.0.5 on 2020-06-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='stores',
            field=models.ManyToManyField(to='main_app.Store'),
        ),
    ]
